### PR TITLE
dockerfile: fix unicode warning. See exercism/prolog#170

### PR DESCRIPTION
**Pull request by sudhackar**
See Issue : exercism/prolog#170
Before Fix
```bash
root@e1a4478f3dcd:/solution# swipl -f *.pl -s *.plt -g run_tests,halt -t 'halt(1)'
Warning: /solution/anagram_tests.plt:55:
Warning:    '/solution/anagram_tests.plt':56:80: Illegal multibyte Sequence
Warning: /solution/anagram_tests.plt:58:
Warning:    '/solution/anagram_tests.plt':59:40: Illegal multibyte Sequence
% PL-Unit: anagram ...............
ERROR:
    [[ EXCEPTION while printing message url('/solution/anagram_tests.plt':55)
       with arguments []:
       raised: type_error(text,url('/solution/anagram_tests.plt':55))
    ]]
:
        test detects_unicode_anagrams: failed

.. done
% 1 test failed
% 17 tests passed
ERROR: -g run_tests,halt: false
```

After fix
```bash
$ docker run -it --rm --entrypoint /bin/sh --name test -v /home/sudhakar/tools/exercism/prolog/anagram/:/solution -v /tmp/out:/output exercism/prolog-test-runner
# bash
root@392299eaffb9:/opt/test-runner# cd /solution
root@392299eaffb9:/solution# swipl -f *.pl -s *.plt -g run_tests,halt -t 'halt(1)'
% PL-Unit: anagram .................. done
% All 18 tests passed
root@392299eaffb9:/solution# env | grep UTF-8
LANG=C.UTF-8
LC_ALL=C.UTF-8
root@392299eaffb9:/solution# exit
#
```

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
It looks like these changes influence the output of the test runner. See https://github.com/exercism/prolog-test-runner/runs/6212182841?check_suite_focus=true.
Could you update the expected results?

**Comment by sudhackar** [comment]
Will do. Thanks!

**Comment by sudhackar** [comment]
This change is not responsible for the changed output. Here I diff with the current master based docker image
```bash
[/tmp] for i in  /tmp/old/tests/* ; do echo $i; diff $i/results.json /tmp/prolog-test-runner/tests/$i:t:r/results.json ;  done
/tmp/old/tests/example-all-fail
/tmp/old/tests/example-empty-file
/tmp/old/tests/example-partial-fail
/tmp/old/tests/example-success
/tmp/old/tests/example-syntax-error
```
I'll update the new content. Its likely due to internal changes in swipl and us not fixing a specific version to test for `swipl` installation in docker

**Comment by sudhackar** [comment]
Passes now on local
```bash
[prolog-test-runner] ./bin/run-tests-in-docker.sh                                                                                                            20:54:42  ☁  fix-unicode-warning ☂ ⚡
example-all-fail: testing...
example-all-fail: done
example-all-fail: comparing results.json to expected_results.json
example-empty-file: testing...
example-empty-file: done
example-empty-file: comparing results.json to expected_results.json
example-partial-fail: testing...
example-partial-fail: done
example-partial-fail: comparing results.json to expected_results.json
example-success: testing...
example-success: done
example-success: comparing results.json to expected_results.json
example-syntax-error: testing...
example-syntax-error: done
example-syntax-error: comparing results.json to expected_results.json
```

**Comment by ErikSchierboom** [comment]
> [...] us not fixing a specific version to test for swipl installation in docker

This is probably something we should be doing. Care to make another PR to do that? :)

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks a ton!

**Comment by sudhackar** [comment]
> > [...] us not fixing a specific version to test for swipl installation in docker
> 
> This is probably something we should be doing. Care to make another PR to do that? :)

Definitely

**Pull request merged**
